<a href="https://colab.research.google.com/github/CesarAugusto88/Trabalho_IA_RNA/blob/main/Trabalho_IA_BackPropagation_conjunto_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Inteligência Artificial

# Aprendizagem de Máquina

# Prof. Elcio Hideiti Shiguemori
## Cesar Augusto de Moraes Costa 330807/2022

**Importando as bibliotecas**

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, normalize, MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

**Carregamento dos dados**

In [66]:
!gdown --id 19DHNrSH1lMbqy6AowqzuiaspYAnAY6E3


/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=19DHNrSH1lMbqy6AowqzuiaspYAnAY6E3
To: /content/S220201008.csv
100% 99.5M/99.5M [00:00<00:00, 224MB/s]


In [67]:
!gdown --id 18QkzQAFqL6DfV9-JdIDYll3wSkdEav_l

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=18QkzQAFqL6DfV9-JdIDYll3wSkdEav_l
To: /content/S120201007.csv
100% 36.4M/36.4M [00:00<00:00, 161MB/s]


**Pré-processamento**

In [68]:
pd.set_option('display.max_columns', None)  # para mostrar todas colunas

In [69]:
m_1=pd.read_csv('S120201007.csv')
m_1

fid  DN  20201007_S1_VH_count  20201007_S1_VH_sum  \
0       1250   3                  24.0            0.633654   
1       1251  33                  40.0            0.899754   
2       1274   3                  22.0            0.622369   
3       1282   4                  32.0            0.492804   
4       1283  33                   3.0            0.093754   
...      ...  ..                   ...                 ...   
90059  98176   3               48522.0         1856.529188   
90060  98177  39                6482.0           47.904245   
90061  98196  39                6353.0           42.290508   
90062  98213   3              177312.0         6431.275320   
90063  98228  39              458715.0         1512.508805   

       20201007_S1_VH_mean  20201007_S1_VH_median  20201007_S1_VH_stdev  \
0                 0.026402               0.024943              0.014827   
1                 0.022494               0.018994              0.014032   
2                 0.028289               0.025780              0.013895   
3                 0.015400               0.013414              0.006689   
4                 0.031251               0.030557              0.004536   
...                    ...                    ...                   ...   
90059             0.038262               0.033966              0.020084   
90060             0.007390               0.006470              0.004631   
90061             0.006657               0.005685              0.004313   
90062             0.036271               0.032136              0.019893   
90063             0.003297               0.002698              0.002741   

       20201007_S1_VH_min  20201007_S1_VH_max  20201007_S1_VH_range  \
0                0.005854            0.077908              0.072054   
1                0.005554            0.063726              0.058172   
2                0.010080            0.068227              0.058147   
3                0.006707            0.037720              0.031013   
4                0.026076            0.037121              0.011045   
...                   ...                 ...                   ...   
90059            0.001464            0.249638              0.248173   
90060            0.000982            0.087139              0.086157   
90061            0.000198            0.091714              0.091516   
90062            0.000929            0.370145              0.369216   
90063            0.000204            0.184535              0.184331   

       20201007_S1_VH_minority  20201007_S1_VH_majority  \
0                     0.005854                 0.005854   
1                     0.005554                 0.005554   
2                     0.010080                 0.010080   
3                     0.006707                 0.006707   
4                     0.026076                 0.026076   
...                        ...                      ...   
90059                 0.001464                 0.072416   
90060                 0.000982                 0.003554   
90061                 0.000198                 0.002831   
90062                 0.000929                 0.022183   
90063                 0.000204                 0.001050   

       20201007_S1_VH_variety  20201007_S1_VH_variance  20201007_S1_VV_count  \
0                          24                 0.000220                  24.0   
1                          40                 0.000197                  40.0   
2                          22                 0.000193                  22.0   
3                          32                 0.000045                  32.0   
4                           3                 0.000021                   3.0   
...                       ...                      ...                   ...   
90059                   48151                 0.000403               48522.0   
90060                    6435                 0.000021                6482.0   
90061                    6286                 0.000019                6353.0   
9

In [70]:
m_2=pd.read_csv('S220201008.csv')
m_2

fid  DN  20201008_S2_B1_count  20201008_S2_B1_sum  \
0       1250   3              1.375895        1.948452e+03   
1       1251  33              2.000000        2.722000e+03   
2       1274   3              3.000000        4.252000e+03   
3       1282   4              2.000000        2.934000e+03   
4       1283  33              0.187886        2.603981e+02   
...      ...  ..                   ...                 ...   
90059  98176   3           2587.000000        3.688141e+06   
90060  98177  39            351.000000        5.596130e+05   
90061  98196  39            333.000000        5.106280e+05   
90062  98213   3           9467.000000        1.342127e+07   
90063  98228  39          24299.000000        3.985844e+07   

       20201008_S2_B1_mean  20201008_S2_B1_median  20201008_S2_B1_stdev  \
0              1416.133981                 1413.0             21.854578   
1              1361.000000                 1361.0              3.000000   
2              1417.333333                 1418.0              1.699673   
3              1467.000000                 1467.0              4.000000   
4              1385.937377                 1386.5              2.562527   
...                    ...                    ...                   ...   
90059          1425.643989                 1420.0             23.180783   
90060          1594.339031                 1593.0             31.360356   
90061          1533.417417                 1536.0             17.583518   
90062          1417.690293                 1417.0             40.544410   
90063          1640.332359                 1639.0             52.374787   

       20201008_S2_B1_min  20201008_S2_B1_max  20201008_S2_B1_range  \
0                  1393.0              1458.0                  65.0   
1                  1358.0              1364.0                   6.0   
2                  1415.0              1419.0                   4.0   
3                  1463.0              1471.0                   8.0   
4                  1384.0              1389.0                   5.0   
...                   ...                 ...                   ...   
90059              1383.0              1597.0                 214.0   
90060              1497.0              1687.0                 190.0   
90061              1451.0              1560.0                 109.0   
90062              1337.0              1660.0                 323.0   
90063              1446.0              2206.0                 760.0   

       20201008_S2_B1_minority  20201008_S2_B1_majority  \
0                       1393.0                   1393.0   
1                       1358.0                   1358.0   
2                       1415.0                   1415.0   
3                       1463.0                   1463.0   
4                       1384.0                   1384.0   
...                        ...                      ...   
90059                   1383.0                   1411.0   
90060                   1497.0                   1594.0   
90061                   1451.0                   1543.0   
90062                   1337.0                   1409.0   
90063                   1446.0                   1598.0   

       20201008_S2_B1_variety  20201008_S2_B1_variance  20201008_S2_B2_count  \
0                         8.0               477.622559                  51.0   
1                         2.0                 9.000000                  68.0   
2                         3.0                 2.888889                  42.0   
3                         2.0                16.000000                  72.0   
4                         2.0                 6.566544                   6.0   
...                       ...                      ...                   ...   
90059                   155.0               537.348710               93170.0   
90060                   106.0               983.471952               12484.0   
90061                    69.0               309.180117               12337.0   
9

In [71]:
dados = pd.merge(m_1, m_2, how='inner', on=('fid','DN'))  # Mesclagem dos dados com junção interna de colunas fid e Digital Number (DN)

In [72]:
dados

fid  DN  20201007_S1_VH_count  20201007_S1_VH_sum  \
0       1250   3                  24.0            0.633654   
1       1251  33                  40.0            0.899754   
2       1274   3                  22.0            0.622369   
3       1282   4                  32.0            0.492804   
4       1283  33                   3.0            0.093754   
...      ...  ..                   ...                 ...   
90059  98176   3               48522.0         1856.529188   
90060  98177  39                6482.0           47.904245   
90061  98196  39                6353.0           42.290508   
90062  98213   3              177312.0         6431.275320   
90063  98228  39              458715.0         1512.508805   

       20201007_S1_VH_mean  20201007_S1_VH_median  20201007_S1_VH_stdev  \
0                 0.026402               0.024943              0.014827   
1                 0.022494               0.018994              0.014032   
2                 0.028289               0.025780              0.013895   
3                 0.015400               0.013414              0.006689   
4                 0.031251               0.030557              0.004536   
...                    ...                    ...                   ...   
90059             0.038262               0.033966              0.020084   
90060             0.007390               0.006470              0.004631   
90061             0.006657               0.005685              0.004313   
90062             0.036271               0.032136              0.019893   
90063             0.003297               0.002698              0.002741   

       20201007_S1_VH_min  20201007_S1_VH_max  20201007_S1_VH_range  \
0                0.005854            0.077908              0.072054   
1                0.005554            0.063726              0.058172   
2                0.010080            0.068227              0.058147   
3                0.006707            0.037720              0.031013   
4                0.026076            0.037121              0.011045   
...                   ...                 ...                   ...   
90059            0.001464            0.249638              0.248173   
90060            0.000982            0.087139              0.086157   
90061            0.000198            0.091714              0.091516   
90062            0.000929            0.370145              0.369216   
90063            0.000204            0.184535              0.184331   

       20201007_S1_VH_minority  20201007_S1_VH_majority  \
0                     0.005854                 0.005854   
1                     0.005554                 0.005554   
2                     0.010080                 0.010080   
3                     0.006707                 0.006707   
4                     0.026076                 0.026076   
...                        ...                      ...   
90059                 0.001464                 0.072416   
90060                 0.000982                 0.003554   
90061                 0.000198                 0.002831   
90062                 0.000929                 0.022183   
90063                 0.000204                 0.001050   

       20201007_S1_VH_variety  20201007_S1_VH_variance  20201007_S1_VV_count  \
0                          24                 0.000220                  24.0   
1                          40                 0.000197                  40.0   
2                          22                 0.000193                  22.0   
3                          32                 0.000045                  32.0   
4                           3                 0.000021                   3.0   
...                       ...                      ...                   ...   
90059                   48151                 0.000403               48522.0   
90060                    6435                 0.000021                6482.0   
90061                    6286                 0.000019                6353.0   
9

In [73]:
dados.describe()

fid            DN  20201007_S1_VH_count  20201007_S1_VH_sum  \
count  90064.000000  90064.000000          9.006400e+04        90064.000000   
mean   48389.389634     21.661019          6.776633e+02           16.289841   
std    27074.337396     13.797223          3.924570e+04         1442.962452   
min     1250.000000      0.000000          5.796981e-02            0.000177   
25%    24856.750000     15.000000          4.000000e+00            0.092589   
50%    48204.500000     15.000000          1.000000e+01            0.224516   
75%    71790.250000     41.000000          3.200000e+01            0.749830   
max    98228.000000     41.000000          9.348954e+06       365097.349090   

       20201007_S1_VH_mean  20201007_S1_VH_median  20201007_S1_VH_stdev  \
count         90064.000000           90064.000000          90064.000000   
mean              0.023559               0.021240              0.011417   
std               0.015475               0.014654              0.009433   
min               0.001012               0.001030              0.000059   
25%               0.010327               0.008644              0.004328   
50%               0.021644               0.018833              0.009792   
75%               0.034081               0.030981              0.016497   
max               0.613324               0.415338              0.717222   

       20201007_S1_VH_min  20201007_S1_VH_max  20201007_S1_VH_range  \
count        90064.000000        90064.000000          90064.000000   
mean             0.009499            0.054268              0.044768   
std              0.008823            0.057297              0.056700   
min              0.000001            0.001135              0.000156   
25%              0.003208            0.021241              0.013751   
50%              0.006486            0.044948              0.032285   
75%              0.013032            0.074432              0.062397   
max              0.193442            7.358577              7.357736   

       20201007_S1_VH_minority  20201007_S1_VH_majority  \
count             90064.000000             90064.000000   
mean                  0.009523                 0.010067   
std                   0.008883                 0.009409   
min                   0.000001                 0.000023   
25%                   0.003213                 0.003406   
50%                   0.006497                 0.006921   
75%                   0.013054                 0.013744   
max                   0.193442                 0.193442   

       20201007_S1_VH_variety  20201007_S1_VH_variance  20201007_S1_VV_count  \
count            9.006400e+04             9.006400e+04          9.006400e+04   
mean             6.426666e+02             2.193336e-04          6.776633e+02   
std              3.364956e+04             1.901603e-03          3.924570e+04   
min              2.000000e+00             3.536456e-09          5.796981e-02   
25%              4.000000e+00             1.872779e-05          4.000000e+00   
50%              1.000000e+01             9.587613e-05          1.000000e+01   
75%              3.200000e+01             2.721540e-04          3.200000e+01   
max              7.581872e+06             5.144076e-01          9.348954e+06   

       20201007_S1_VV_sum  20201007_S1_VV_mean  20201007_S1_VV_median  \
count        9.006400e+04         90064.000000           90064.000000   
mean         6.525446e+01             0.095354               0.085079   
std          5.676950e+03             0.097781               0.089576   
min          9.915597e-04             0.004879               0.004451   
25%          3.813199e-01             0.044820               0.038153   
50%          9.205673e-01             0.086977               0.075612   
75%          3.011974e+00             0.132477               0.119365   
max          1.429232e+06            17.523796              19.148685   

       20201007_S1_VV_stdev  20201007_S1_VV_min  20201007_S1_VV_max  \
count 

In [74]:
dados.isna().sum()  # verificação de dados faltantes

fid                          0
DN                           0
20201007_S1_VH_count         0
20201007_S1_VH_sum           0
20201007_S1_VH_mean          0
                            ..
20201008_S2_B12_range       21
20201008_S2_B12_minority    21
20201008_S2_B12_majority    21
20201008_S2_B12_variety     21
20201008_S2_B12_variance    21
Length: 182, dtype: int64

In [75]:
dados2 = dados.dropna()  # Remove dados faltantes
dados2 = dados2.drop(columns=['fid'])  # remove coluna fid
dados2.tail(40)

DN  20201007_S1_VH_count  20201007_S1_VH_sum  20201007_S1_VH_mean  \
90024  15          4.000000e+00            0.168749             0.042187   
90025  15          9.800000e+01            3.558265             0.036309   
90026  15          1.000000e+01            0.428007             0.042801   
90027  15          6.000000e+00            0.184931             0.030822   
90028  12          1.000000e+03           20.083241             0.020083   
90029  41          9.481893e-01            0.050391             0.053144   
90030  41          1.500000e+01            0.424947             0.028330   
90031  41          1.500000e+02            1.072383             0.007149   
90032   3          9.173000e+03          363.254624             0.039600   
90033  39          5.190000e+02            2.264756             0.004364   
90034  11          2.800000e+01            0.719374             0.025692   
90035  15          5.810000e+02            6.734234             0.011591   
90036  15          1.946000e+03           15.305983             0.007865   
90037  15          3.740000e+03           33.893277             0.009062   
90038  39          9.492800e+04          483.164268             0.005090   
90039  33          7.900000e+01            2.245898             0.028429   
90040  12          8.160000e+02           24.406842             0.029910   
90041   4          1.730000e+02            6.169045             0.035659   
90042  15          4.015000e+03           71.745000             0.017869   
90043  15          4.699500e+04          385.320957             0.008199   
90044  39          7.177300e+04          334.453192             0.004660   
90045  39          9.300000e+01            0.504396             0.005424   
90046  15          4.200000e+01            1.518636             0.036158   
90047   3          2.878100e+04          983.831772             0.034183   
90048  39          7.228100e+04          385.966779             0.005340   
90049  39          7.907400e+04          424.970436             0.005374   
90050  39          6.260000e+03           27.435885             0.004383   
90051   3          9.348954e+06       365097.349090             0.039052   
90052   3          2.028350e+05         7737.773049             0.038148   
90053  24          7.398100e+04         1817.699504             0.024570   
90054  39          3.442910e+05         2456.360136             0.007135   
90055  39          1.028840e+05          462.078876             0.004491   
90056   3          1.190400e+04          488.667456             0.041051   
90057   3          1.557443e+06        54969.635289             0.035295   
90058  33          9.464550e+05         8095.689764             0.008554   
90059   3          4.852200e+04         1856.529188             0.038262   
90060  39          6.482000e+03           47.904245             0.007390   
90061  39          6.353000e+03           42.290508             0.006657   
90062   3          1.773120e+05         6431.275320             0.036271   
90063  39          4.587150e+05         1512.508805             0.003297   

       20201007_S1_VH_median  20201007_S1_VH_stdev  20201007_S1_VH_min  \
90024               0.042580              0.009936            0.030152   
90025               0.030964              0.025791            0.002708   
90026               0.037061              0.020123            0.019920   
90027               0.030812              0.013118            0.009326   
90028               0.016324              0.014351            0.002104   
90029               0.043413              0.016857            0.019091   
90030               0.019466              0.019870            0.006662   
90031               0.005580              0.006046            0.001341   
90032               0.034891              0.022122            0.003841   
90033               0.004016              0.001993            0.000979   
90034               0.026552              0.014213            0.005860   
90

In [76]:
y_treino = np.array(dados2[dados2.columns[0]])
x_treino = np.array(dados2[dados2.columns[1:181]])

In [77]:
# Normalização com StandardScaler
escale = StandardScaler()
escale.fit(x_treino)
x_norm = escale.transform(x_treino)

#Função train_test_split

É uma função de seleção de **modelo do Sklearn** para dividir matrizes de dados em **dois subconjuntos**: dados de treinamento e dados de teste. Por padrão, essa função faz partições aleatórias para os dois conjuntos. Entretanto, é possível especificar um estado aleatório para a operação.

```
-------------------------------------------------------------------------------
Função train_test_split(X, y, train-size=None, test_size=None,
                        random_state=None, shuffle = True, stratify = None)
-------------------------------------------------------------------------------
Entrada: | X e y      --> São o conjunto de dados que serão utilizados. 
         | train_size --> Define o tamanho do conjunto de dados de treinamento.
         |                Existem 3 opções: 
         |                     None --> padrão
         |                     Int --> requer o número exato de amostras
         |                     Float --> varua de 0.1 a 1.0.
         | test_size --> Especifica o tamanho do conjunto de dados de teste. O  
         |               estado padrão se adapta ao tamanho do treinamento.
         |               Será definido como 0.25 se o tamanho do treinamento
         |               for definido como padrão.
         | radom_state --> O modo padrão executa uma divisão aleatória usando
         |                 **np.random**. Como alternativa, você pode adicionar 
         |                 um número inteiro usando um número exato.
         | shuffle --> Se deve ou não embaralhar os dados antes de dividir. 
         |             Se shuffle = False, stratify deve ser igual a None.
         | stratify --> Se for igual a None, os dados são divididos de forma
         | estratificados  
---------|--------------------------------------------------------------------- 
Saída    | retorna os conjuntos de treinamento e teste
         |      --> X_train, X_test, y_train e y_test
-------------------------------------------------------------------------------
```

In [78]:
x_train, x_test, y_train, y_test = train_test_split(x_norm, y_treino, stratify=y_treino, random_state=1)

In [79]:
x_train.shape

(67532, 180)

In [80]:
x_test.shape

(22511, 180)

In [81]:
# net = MLPClassifier(hidden_layer_sizes=(10,100,17 ), activation='tanh', solver='sgd', 
#                    alpha=0.0001, batch_size=200, learning_rate='adaptive', 
#                     learning_rate_init=0.2, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.7, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)
# net = MLPClassifier(hidden_layer_sizes=(22,22,64 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=200, learning_rate='adaptive', 
#                     learning_rate_init=0.2, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)
# net = MLPClassifier(hidden_layer_sizes=(22,22,22 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=100, learning_rate='adaptive', 
#                     learning_rate_init=0.2, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8) # 47, ... 65 ...
# net = MLPClassifier(hidden_layer_sizes=(44,33,22 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=70, learning_rate='adaptive', 
#                     learning_rate_init=0.4, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)
# net = MLPClassifier(hidden_layer_sizes=(44,33,22 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size='auto', learning_rate='adaptive', 
#                     learning_rate_init=0.5, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)  # 65,7
# net = MLPClassifier(hidden_layer_sizes=(100,33,50 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=300, learning_rate='adaptive', 
#                     learning_rate_init=0.2, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.7, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)  # 65,99
net = MLPClassifier(hidden_layer_sizes=(100,70,50 ), activation='relu', solver='adam', 
                   alpha=0.0001, batch_size='auto', learning_rate='constant', 
                    learning_rate_init=0.001, max_iter=200,  
                    verbose=True,  
                    momentum=0.9, early_stopping=True, 
                    validation_fraction=0.1, n_iter_no_change=9) # 66
# net = MLPClassifier(hidden_layer_sizes=(100,50 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=500, learning_rate='adaptive', 
#                     learning_rate_init=0.3, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)# 66,14%
# net = MLPClassifier(hidden_layer_sizes=(100,50,65 ), activation='tanh', solver='sgd', 
#                    alpha=0.01, batch_size=200, learning_rate='adaptive', 
#                     learning_rate_init=0.3, max_iter=500, tol=0.0001,
#                     verbose=True,  
#                     momentum=0.7, early_stopping=True, 
#                     validation_fraction=0.01, n_iter_no_change=4)

In [82]:
net.fit(x_train,y_train)

Iteration 1, loss = 1.06667453
Validation score: 0.616672
Iteration 2, loss = 0.94514894
Validation score: 0.632366
Iteration 3, loss = 0.91259016
Validation score: 0.629849
Iteration 4, loss = 0.89077824
Validation score: 0.638881
Iteration 5, loss = 0.87611771
Validation score: 0.648357
Iteration 6, loss = 0.85953851
Validation score: 0.648505
Iteration 7, loss = 0.84894997
Validation score: 0.647320
Iteration 8, loss = 0.84102244
Validation score: 0.652946
Iteration 9, loss = 0.83288300
Validation score: 0.654575
Iteration 10, loss = 0.82510967
Validation score: 0.656500
Iteration 11, loss = 0.81764964
Validation score: 0.658869
Iteration 12, loss = 0.81072309
Validation score: 0.652798
Iteration 13, loss = 0.80706831
Validation score: 0.659165
Iteration 14, loss = 0.80121409
Validation score: 0.664199
Iteration 15, loss = 0.79489107
Validation score: 0.659461
Iteration 16, loss = 0.78917247
Validation score: 0.661386
Iteration 17, loss = 0.78507786
Validation score: 0.664791
Iterat

MLPClassifier(early_stopping=True, hidden_layer_sizes=(100, 70, 50),
              n_iter_no_change=9, verbose=True)

In [83]:
predict = net.predict(x_test)

In [84]:
predict

array([15, 15, 41, ..., 15, 15, 15])

In [85]:
print('Acurácia: {}%' .format(round(net.score(x_test, y_test) * 100,4)))

Acurácia: 65.99%


In [86]:
print(confusion_matrix(y_test, predict))
print(classification_report(y_test, predict))

[[   0    4    1    0    2    6    0    0    0    1]
 [   0 1170   37    1  118 1080    0   18    0   83]
 [   0   81  186    6   59  156    0    5    0   11]
 [   0   23   27    8   44   33    0    6    0   11]
 [   0  152   70    9  325  504    0   22    1  140]
 [   0  518   74    2  124 7734    0   41    7 2114]
 [   0    0    0    0    1    0    2    0    0    3]
 [   0   39   15    1   90  106    0  125    0   44]
 [   0    3    0    0    0   57    0    0  101  549]
 [   0   39    1    0   28 1035    0   17   37 5204]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           3       0.58      0.47      0.52      2507
           4       0.45      0.37      0.41       504
          11       0.30      0.05      0.09       152
          12       0.41      0.27      0.32      1223
          15       0.72      0.73      0.73     10614
          24       1.00      0.33      0.50         6
          33       0.53      0.30   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
