<a href="https://colab.research.google.com/github/CesarAugusto88/Trabalho_IA_RNA/blob/main/Trabalho_IA_BackPropagation_conj_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Inteligência Artificial

# Aprendizagem de Máquina

# Prof. Elcio Hideiti Shiguemori
## Cesar Augusto de Moraes Costa 330807/2022

**Importando as bibliotecas**

In [402]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, normalize, MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

**Carregamento dos dados**

In [403]:
!gdown --id 1cY5vm70qGOBnryYQoaBrN47NybTMILAq


/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1cY5vm70qGOBnryYQoaBrN47NybTMILAq
To: /content/S120200528.csv
100% 36.1M/36.1M [00:00<00:00, 58.8MB/s]


In [404]:
!gdown --id 1MfNg2Qd3zxbV2Qwz5rRZifmAgIVm2UKT

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1MfNg2Qd3zxbV2Qwz5rRZifmAgIVm2UKT
To: /content/S220200531.csv
100% 100M/100M [00:01<00:00, 61.8MB/s] 


**Pré-processamento**

In [405]:
pd.set_option('display.max_columns', None)  # para mostrar todas colunas

In [406]:
m_1=pd.read_csv('S120200528.csv')
m_1

fid  DN  S1_20200528_VHcount  S1_20200528_VHsum  S1_20200528_VHmean  \
0       1250   3                 27.0           0.795952            0.029480   
1       1251  33                 40.0           0.987869            0.024697   
2       1274   3                 22.0           0.593056            0.026957   
3       1282   4                 36.0           0.988538            0.027459   
4       1283  33                  2.0           0.058888            0.029444   
...      ...  ..                  ...                ...                 ...   
90059  98176   3              48425.0        1969.477428            0.040671   
90060  98177  39               6482.0         281.328242            0.043401   
90061  98196  39               6372.0         128.996088            0.020244   
90062  98213   3             177254.0        6890.852883            0.038876   
90063  98228  39             458715.0        7729.274786            0.016850   

       S1_20200528_VHmedian  S1_20200528_VHstdev  S1_20200528_VHmin  \
0                  0.026813             0.012523           0.013947   
1                  0.021505             0.014039           0.002930   
2                  0.024638             0.009006           0.014618   
3                  0.023446             0.014222           0.006988   
4                  0.029444             0.007081           0.022363   
...                     ...                  ...                ...   
90059              0.036105             0.021721           0.002518   
90060              0.039342             0.021112           0.003075   
90061              0.018514             0.009395           0.002174   
90062              0.034384             0.021388           0.000590   
90063              0.013576             0.011877           0.000621   

       S1_20200528_VHmax  S1_20200528_VHrange  S1_20200528_VHminority  \
0               0.067887             0.053940                0.013947   
1               0.079253             0.076323                0.002930   
2               0.044852             0.030234                0.014618   
3               0.069067             0.062079                0.006988   
4               0.036525             0.014161                0.022363   
...                  ...                  ...                     ...   
90059           0.265330             0.262811                0.002518   
90060           0.174765             0.171690                0.003075   
90061           0.086027             0.083853                0.002174   
90062           0.316217             0.315627                0.000590   
90063           0.189162             0.188540                0.000621   

       S1_20200528_VHmajority  S1_20200528_VHvariety  S1_20200528_VHvariance  \
0                    0.013947                     27                0.000157   
1                    0.002930                     40                0.000197   
2                    0.014618                     22                0.000081   
3                    0.006988                     36                0.000202   
4                    0.022363                      2                0.000050   
...                       ...                    ...                     ...   
90059                0.007512                  48045                0.000472   
90060                0.008979                   6434                0.000446   
90061                0.007509                   6307                0.000088   
90062                0.016016                 175451                0.000457   
90063                0.004059                 451987                0.000141   

       S1_20200528_VV_count  S1_20200528_VV_sum  S1_20200528_VV_mean  \
0                      27.0            4.219886             0.156292   
1                      40.0            3.479310             0.086983   
2                      22.0            2.316674             0.105303   
3                      36.0            3.803303             0.105647 

In [407]:
m_2=pd.read_csv('S220200531.csv')
m_2

fid  DN  20200531_S2_B1_count  20200531_S2_B1_sum  \
0       1250   3              1.375895        1.490411e+03   
1       1251  33              2.000000        2.086000e+03   
2       1274   3              3.000000        3.258000e+03   
3       1282   4              2.000000        2.346000e+03   
4       1283  33              0.187886        2.021230e+02   
...      ...  ..                   ...                 ...   
90059  98176   3           2587.000000        2.776720e+06   
90060  98177  39            351.000000        4.042810e+05   
90061  98196  39            333.000000        3.811870e+05   
90062  98213   3           9467.000000        1.051045e+07   
90063  98228  39          24299.000000        2.865165e+07   

       20200531_S2_B1_mean  20200531_S2_B1_median  20200531_S2_B1_stdev  \
0              1083.229878                 1082.0             14.611335   
1              1043.000000                 1043.0              4.000000   
2              1086.000000                 1085.0              2.160247   
3              1173.000000                 1173.0              3.000000   
4              1075.774951                 1076.0              1.025011   
...                    ...                    ...                   ...   
90059          1073.335910                 1071.0             10.203024   
90060          1151.797721                 1153.0              9.268185   
90061          1144.705706                 1144.0              5.887626   
90062          1110.219499                 1106.0             13.855438   
90063          1179.128935                 1147.0             76.156739   

       20200531_S2_B1_min  20200531_S2_B1_max  20200531_S2_B1_range  \
0                  1069.0              1110.0                  41.0   
1                  1039.0              1047.0                   8.0   
2                  1084.0              1089.0                   5.0   
3                  1170.0              1176.0                   6.0   
4                  1075.0              1077.0                   2.0   
...                   ...                 ...                   ...   
90059              1058.0              1144.0                  86.0   
90060              1116.0              1185.0                  69.0   
90061              1120.0              1165.0                  45.0   
90062              1088.0              1319.0                 231.0   
90063              1080.0              1481.0                 401.0   

       20200531_S2_B1_minority  20200531_S2_B1_majority  \
0                       1069.0                   1069.0   
1                       1039.0                   1039.0   
2                       1084.0                   1084.0   
3                       1170.0                   1170.0   
4                       1075.0                   1075.0   
...                        ...                      ...   
90059                   1113.0                   1071.0   
90060                   1116.0                   1154.0   
90061                   1120.0                   1144.0   
90062                   1162.0                   1100.0   
90063                   1080.0                   1130.0   

       20200531_S2_B1_variety  20200531_S2_B1_variance  20200531_S2_B2_count  \
0                         8.0               213.491104                  51.0   
1                         2.0                16.000000                  68.0   
2                         3.0                 4.666667                  42.0   
3                         2.0                 9.000000                  72.0   
4                         2.0                 1.050647                   6.0   
...                       ...                      ...                   ...   
90059                    70.0               104.101698               93170.0   
90060                    52.0                85.899254               12484.0   
90061                    35.0                34.664142               12337.0   
9

In [408]:
# Mesclagem com junção interna de colunas fid , Digital Number (DN) 
dados = pd.merge(m_1, m_2, how='inner', on=('fid','DN'))
dados

fid  DN  S1_20200528_VHcount  S1_20200528_VHsum  S1_20200528_VHmean  \
0       1250   3                 27.0           0.795952            0.029480   
1       1251  33                 40.0           0.987869            0.024697   
2       1274   3                 22.0           0.593056            0.026957   
3       1282   4                 36.0           0.988538            0.027459   
4       1283  33                  2.0           0.058888            0.029444   
...      ...  ..                  ...                ...                 ...   
90059  98176   3              48425.0        1969.477428            0.040671   
90060  98177  39               6482.0         281.328242            0.043401   
90061  98196  39               6372.0         128.996088            0.020244   
90062  98213   3             177254.0        6890.852883            0.038876   
90063  98228  39             458715.0        7729.274786            0.016850   

       S1_20200528_VHmedian  S1_20200528_VHstdev  S1_20200528_VHmin  \
0                  0.026813             0.012523           0.013947   
1                  0.021505             0.014039           0.002930   
2                  0.024638             0.009006           0.014618   
3                  0.023446             0.014222           0.006988   
4                  0.029444             0.007081           0.022363   
...                     ...                  ...                ...   
90059              0.036105             0.021721           0.002518   
90060              0.039342             0.021112           0.003075   
90061              0.018514             0.009395           0.002174   
90062              0.034384             0.021388           0.000590   
90063              0.013576             0.011877           0.000621   

       S1_20200528_VHmax  S1_20200528_VHrange  S1_20200528_VHminority  \
0               0.067887             0.053940                0.013947   
1               0.079253             0.076323                0.002930   
2               0.044852             0.030234                0.014618   
3               0.069067             0.062079                0.006988   
4               0.036525             0.014161                0.022363   
...                  ...                  ...                     ...   
90059           0.265330             0.262811                0.002518   
90060           0.174765             0.171690                0.003075   
90061           0.086027             0.083853                0.002174   
90062           0.316217             0.315627                0.000590   
90063           0.189162             0.188540                0.000621   

       S1_20200528_VHmajority  S1_20200528_VHvariety  S1_20200528_VHvariance  \
0                    0.013947                     27                0.000157   
1                    0.002930                     40                0.000197   
2                    0.014618                     22                0.000081   
3                    0.006988                     36                0.000202   
4                    0.022363                      2                0.000050   
...                       ...                    ...                     ...   
90059                0.007512                  48045                0.000472   
90060                0.008979                   6434                0.000446   
90061                0.007509                   6307                0.000088   
90062                0.016016                 175451                0.000457   
90063                0.004059                 451987                0.000141   

       S1_20200528_VV_count  S1_20200528_VV_sum  S1_20200528_VV_mean  \
0                      27.0            4.219886             0.156292   
1                      40.0            3.479310             0.086983   
2                      22.0            2.316674             0.105303   
3                      36.0            3.803303             0.105647 

In [409]:
dados.describe()

fid            DN  S1_20200528_VHcount  S1_20200528_VHsum  \
count  90064.000000  90064.000000         9.006400e+04       90064.000000   
mean   48389.389634     21.661019         6.776614e+02          21.447613   
std    27074.337396     13.797223         3.924607e+04        1535.672536   
min     1250.000000      0.000000         5.796962e-02           0.000594   
25%    24856.750000     15.000000         4.000000e+00           0.140159   
50%    48204.500000     15.000000         1.000000e+01           0.323187   
75%    71790.250000     41.000000         3.200000e+01           1.021651   
max    98228.000000     41.000000         9.349644e+06      385541.063237   

       S1_20200528_VHmean  S1_20200528_VHmedian  S1_20200528_VHstdev  \
count        90064.000000          90064.000000         90064.000000   
mean             0.031500              0.028800             0.014247   
std              0.015357              0.014551             0.010531   
min              0.001289              0.001398             0.000011   
25%              0.020715              0.018534             0.007509   
50%              0.030526              0.027643             0.012835   
75%              0.040422              0.036948             0.019141   
max              0.649493              0.407688             0.821098   

       S1_20200528_VHmin  S1_20200528_VHmax  S1_20200528_VHrange  \
count       9.006400e+04       90064.000000         90064.000000   
mean        1.332908e-02           0.068923             0.055594   
std         9.907894e-03           0.074058             0.074471   
min         2.792693e-07           0.001768             0.000022   
25%         6.296556e-03           0.036933             0.022399   
50%         1.100326e-02           0.058956             0.043300   
75%         1.764847e-02           0.088707             0.074633   
max         1.842210e-01           8.823542             8.822013   

       S1_20200528_VHminority  S1_20200528_VHmajority  S1_20200528_VHvariety  \
count            9.006400e+04            90064.000000           9.006400e+04   
mean             1.335589e-02                0.014108           6.425918e+02   
std              9.953435e-03                0.010525           3.363981e+04   
min              2.792693e-07                0.000020           2.000000e+00   
25%              6.302827e-03                0.006769           4.000000e+00   
50%              1.101583e-02                0.011608           1.000000e+01   
75%              1.767843e-02                0.018496           3.200000e+01   
max              1.842210e-01                0.184221           7.577280e+06   

       S1_20200528_VHvariance  S1_20200528_VV_count  S1_20200528_VV_sum  \
count            9.006400e+04          9.006400e+04        9.006400e+04   
mean             3.138921e-04          6.776614e+02        8.955239e+01   
std              3.448826e-03          3.924607e+04        6.465281e+03   
min              1.204774e-10          5.796962e-02        3.311148e-03   
25%              5.639197e-05          4.000000e+00        5.721933e-01   
50%              1.647476e-04          1.000000e+01        1.332546e+00   
75%              3.663958e-04          3.200000e+01        4.211699e+00   
max              6.742025e-01          9.349644e+06        1.625898e+06   

       S1_20200528_VV_mean  S1_20200528_VV_median  S1_20200528_VV_stdev  \
count         90064.000000           90064.000000          90064.000000   
mean              0.130686               0.118265              0.062614   
std               0.087740               0.072483              0.097406   
min               0.002796               0.002531              0.000080   
25%               0.082869               0.074191              0.030832   
50%               0.123413               0.110917              0.052696   
75%               0.167039               0.151569              0.080760   
max              10.075905               7.935204             1

In [410]:
dados2=dados.drop(dados.index[[0]])  # "removeu" indice 0 - linha. Outliers
dados2

fid  DN  S1_20200528_VHcount  S1_20200528_VHsum  S1_20200528_VHmean  \
1       1251  33                 40.0           0.987869            0.024697   
2       1274   3                 22.0           0.593056            0.026957   
3       1282   4                 36.0           0.988538            0.027459   
4       1283  33                  2.0           0.058888            0.029444   
5       1289   4                 32.0           0.996099            0.031128   
...      ...  ..                  ...                ...                 ...   
90059  98176   3              48425.0        1969.477428            0.040671   
90060  98177  39               6482.0         281.328242            0.043401   
90061  98196  39               6372.0         128.996088            0.020244   
90062  98213   3             177254.0        6890.852883            0.038876   
90063  98228  39             458715.0        7729.274786            0.016850   

       S1_20200528_VHmedian  S1_20200528_VHstdev  S1_20200528_VHmin  \
1                  0.021505             0.014039           0.002930   
2                  0.024638             0.009006           0.014618   
3                  0.023446             0.014222           0.006988   
4                  0.029444             0.007081           0.022363   
5                  0.026626             0.019254           0.011753   
...                     ...                  ...                ...   
90059              0.036105             0.021721           0.002518   
90060              0.039342             0.021112           0.003075   
90061              0.018514             0.009395           0.002174   
90062              0.034384             0.021388           0.000590   
90063              0.013576             0.011877           0.000621   

       S1_20200528_VHmax  S1_20200528_VHrange  S1_20200528_VHminority  \
1               0.079253             0.076323                0.002930   
2               0.044852             0.030234                0.014618   
3               0.069067             0.062079                0.006988   
4               0.036525             0.014161                0.022363   
5               0.082031             0.070278                0.011753   
...                  ...                  ...                     ...   
90059           0.265330             0.262811                0.002518   
90060           0.174765             0.171690                0.003075   
90061           0.086027             0.083853                0.002174   
90062           0.316217             0.315627                0.000590   
90063           0.189162             0.188540                0.000621   

       S1_20200528_VHmajority  S1_20200528_VHvariety  S1_20200528_VHvariance  \
1                    0.002930                     40                0.000197   
2                    0.014618                     22                0.000081   
3                    0.006988                     36                0.000202   
4                    0.022363                      2                0.000050   
5                    0.011753                     32                0.000371   
...                       ...                    ...                     ...   
90059                0.007512                  48045                0.000472   
90060                0.008979                   6434                0.000446   
90061                0.007509                   6307                0.000088   
90062                0.016016                 175451                0.000457   
90063                0.004059                 451987                0.000141   

       S1_20200528_VV_count  S1_20200528_VV_sum  S1_20200528_VV_mean  \
1                      40.0            3.479310             0.086983   
2                      22.0            2.316674             0.105303   
3                      36.0            3.803303             0.105647   
4                       2.0            0.187223             0.093611 

In [411]:
dados2.isna().sum()  # verificação de dados faltantes

fid                          0
DN                           0
S1_20200528_VHcount          0
S1_20200528_VHsum            0
S1_20200528_VHmean           0
                            ..
20200531_S2_B12_range       21
20200531_S2_B12_minority    21
20200531_S2_B12_majority    21
20200531_S2_B12_variety     21
20200531_S2_B12_variance    21
Length: 182, dtype: int64

In [412]:
dados2 = dados2.dropna()  # Remove dados faltantes
dados2 = dados2.drop(columns=['fid'])  # remove coluna fid
dados2

DN  S1_20200528_VHcount  S1_20200528_VHsum  S1_20200528_VHmean  \
1      33                 40.0           0.987869            0.024697   
2       3                 22.0           0.593056            0.026957   
3       4                 36.0           0.988538            0.027459   
4      33                  2.0           0.058888            0.029444   
5       4                 32.0           0.996099            0.031128   
...    ..                  ...                ...                 ...   
90059   3              48425.0        1969.477428            0.040671   
90060  39               6482.0         281.328242            0.043401   
90061  39               6372.0         128.996088            0.020244   
90062   3             177254.0        6890.852883            0.038876   
90063  39             458715.0        7729.274786            0.016850   

       S1_20200528_VHmedian  S1_20200528_VHstdev  S1_20200528_VHmin  \
1                  0.021505             0.014039           0.002930   
2                  0.024638             0.009006           0.014618   
3                  0.023446             0.014222           0.006988   
4                  0.029444             0.007081           0.022363   
5                  0.026626             0.019254           0.011753   
...                     ...                  ...                ...   
90059              0.036105             0.021721           0.002518   
90060              0.039342             0.021112           0.003075   
90061              0.018514             0.009395           0.002174   
90062              0.034384             0.021388           0.000590   
90063              0.013576             0.011877           0.000621   

       S1_20200528_VHmax  S1_20200528_VHrange  S1_20200528_VHminority  \
1               0.079253             0.076323                0.002930   
2               0.044852             0.030234                0.014618   
3               0.069067             0.062079                0.006988   
4               0.036525             0.014161                0.022363   
5               0.082031             0.070278                0.011753   
...                  ...                  ...                     ...   
90059           0.265330             0.262811                0.002518   
90060           0.174765             0.171690                0.003075   
90061           0.086027             0.083853                0.002174   
90062           0.316217             0.315627                0.000590   
90063           0.189162             0.188540                0.000621   

       S1_20200528_VHmajority  S1_20200528_VHvariety  S1_20200528_VHvariance  \
1                    0.002930                     40                0.000197   
2                    0.014618                     22                0.000081   
3                    0.006988                     36                0.000202   
4                    0.022363                      2                0.000050   
5                    0.011753                     32                0.000371   
...                       ...                    ...                     ...   
90059                0.007512                  48045                0.000472   
90060                0.008979                   6434                0.000446   
90061                0.007509                   6307                0.000088   
90062                0.016016                 175451                0.000457   
90063                0.004059                 451987                0.000141   

       S1_20200528_VV_count  S1_20200528_VV_sum  S1_20200528_VV_mean  \
1                      40.0            3.479310             0.086983   
2                      22.0            2.316674             0.105303   
3                      36.0            3.803303             0.105647   
4                       2.0            0.187223             0.093611   
5                      32.0            3.909745             0.122180   
...    

In [413]:
y_treino = np.array(dados2[dados2.columns[0]])
x_treino = np.array(dados2[dados2.columns[1:181]])

In [414]:
# Normalização com StandardScaler
escale = StandardScaler()
escale.fit(x_treino)
x_norm = escale.transform(x_treino)

#Função train_test_split

É uma função de seleção de **modelo do Sklearn** para dividir matrizes de dados em **dois subconjuntos**: dados de treinamento e dados de teste. Por padrão, essa função faz partições aleatórias para os dois conjuntos. Entretanto, é possível especificar um estado aleatório para a operação.

```
-------------------------------------------------------------------------------
Função train_test_split(X, y, train-size=None, test_size=None,
                        random_state=None, shuffle = True, stratify = None)
-------------------------------------------------------------------------------
Entrada: | X e y      --> São o conjunto de dados que serão utilizados. 
         | train_size --> Define o tamanho do conjunto de dados de treinamento.
         |                Existem 3 opções: 
         |                     None --> padrão
         |                     Int --> requer o número exato de amostras
         |                     Float --> varua de 0.1 a 1.0.
         | test_size --> Especifica o tamanho do conjunto de dados de teste. O  
         |               estado padrão se adapta ao tamanho do treinamento.
         |               Será definido como 0.25 se o tamanho do treinamento
         |               for definido como padrão.
         | radom_state --> O modo padrão executa uma divisão aleatória usando
         |                 **np.random**. Como alternativa, você pode adicionar 
         |                 um número inteiro usando um número exato.
         | shuffle --> Se deve ou não embaralhar os dados antes de dividir. 
         |             Se shuffle = False, stratify deve ser igual a None.
         | stratify --> Se for igual a None, os dados são divididos de forma
         | estratificados  
---------|--------------------------------------------------------------------- 
Saída    | retorna os conjuntos de treinamento e teste
         |      --> X_train, X_test, y_train e y_test
-------------------------------------------------------------------------------
```

In [415]:
x_train, x_test, y_train, y_test = train_test_split(x_norm, y_treino, stratify=y_treino, random_state=1)

In [416]:
x_train.shape

(67531, 180)

In [417]:
x_test.shape

(22511, 180)

In [418]:
# mlp = MLPClassifier(hidden_layer_sizes=(10,100,17 ), activation='tanh', solver='sgd', 
#                    alpha=0.0001, batch_size=200, learning_rate='adaptive', 
#                     learning_rate_init=0.2, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.7, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)
# mlp = MLPClassifier(hidden_layer_sizes=(22,22,64 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=200, learning_rate='adaptive', 
#                     learning_rate_init=0.2, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)
# mlp = MLPClassifier(hidden_layer_sizes=(22,22,22 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=100, learning_rate='adaptive', 
#                     learning_rate_init=0.2, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8) # 47, ... 65 ...
# mlp = MLPClassifier(hidden_layer_sizes=(44,33,22 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=70, learning_rate='adaptive', 
#                     learning_rate_init=0.4, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)
# mlp = MLPClassifier(hidden_layer_sizes=(44,33,22 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size='auto', learning_rate='adaptive', 
#                     learning_rate_init=0.5, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)  # 65,7
# mlp = MLPClassifier(hidden_layer_sizes=(100,33,50 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=300, learning_rate='adaptive', 
#                     learning_rate_init=0.2, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.7, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)  # 65,99
# mlp = MLPClassifier(hidden_layer_sizes=(50,100 ), activation='relu', solver='adam', 
#                    alpha=0.0001, batch_size='auto', learning_rate='constant', 
#                     learning_rate_init=0.001, max_iter=200,  
#                     verbose=True,  
#                     momentum=0.9, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=9) # 66
# mlp = MLPClassifier(hidden_layer_sizes=(100,50 ), activation='logistic', solver='sgd', 
#                    alpha=0.0001, batch_size=500, learning_rate='adaptive', 
#                     learning_rate_init=0.3, max_iter=2000,  
#                     verbose=True,  
#                     momentum=0.8, early_stopping=True, 
#                     validation_fraction=0.1, n_iter_no_change=8)# 66,14%
mlp = MLPClassifier(hidden_layer_sizes=(100,50,65 ), activation='tanh', solver='sgd', 
                   alpha=0.01, batch_size=200, learning_rate='adaptive', 
                    learning_rate_init=0.3, max_iter=500, tol=0.0001,
                    verbose=True,  
                    momentum=0.7, early_stopping=True, 
                    validation_fraction=0.01, n_iter_no_change=4)

In [419]:
mlp.fit(x_train,y_train)

Iteration 1, loss = 1.01128504
Validation score: 0.625740
Iteration 2, loss = 0.93155968
Validation score: 0.597633
Iteration 3, loss = 0.90495422
Validation score: 0.633136
Iteration 4, loss = 0.88943485
Validation score: 0.582840
Iteration 5, loss = 0.87775694
Validation score: 0.550296
Iteration 6, loss = 0.86693733
Validation score: 0.618343
Iteration 7, loss = 0.85654156
Validation score: 0.557692
Iteration 8, loss = 0.85248779
Validation score: 0.640533
Iteration 9, loss = 0.84405937
Validation score: 0.640533
Iteration 10, loss = 0.83896650
Validation score: 0.633136
Iteration 11, loss = 0.83399438
Validation score: 0.639053
Iteration 12, loss = 0.82891010
Validation score: 0.578402
Iteration 13, loss = 0.82560031
Validation score: 0.560651
Validation score did not improve more than tol=0.000100 for 4 consecutive epochs. Setting learning rate to 0.060000
Iteration 14, loss = 0.76982326
Validation score: 0.634615
Iteration 15, loss = 0.75343023
Validation score: 0.644970
Iteratio

MLPClassifier(activation='tanh', alpha=0.01, batch_size=200,
              early_stopping=True, hidden_layer_sizes=(100, 50, 65),
              learning_rate='adaptive', learning_rate_init=0.3, max_iter=500,
              momentum=0.7, n_iter_no_change=4, solver='sgd',
              validation_fraction=0.01, verbose=True)

In [420]:
predict = mlp.predict(x_test)

In [421]:
predict

array([12,  3, 41, ..., 15, 15, 15])

In [422]:
print('Acurácia: {}%' .format(round(mlp.score(x_test, y_test) * 100,4)))

Acurácia: 66.2165%


In [423]:
print(confusion_matrix(y_test, predict))
print(classification_report(y_test, predict))

[[   0    5    0    0    2    5    0    1    0    1]
 [   0 1263   48    6  114  971    0   29    0   76]
 [   0   61  240    6   75  100    0   12    0   10]
 [   0   20   27   19   36   18    0   19    0   13]
 [   0  197   69   15  388  386    0   45    4  119]
 [   0  637   68    8  135 7897    2   40   30 1797]
 [   0    0    0    0    1    1    0    0    0    4]
 [   0   37    7    9   41   94    0  202    0   30]
 [   0    4    1    1    2   86    1    0  180  435]
 [   0   52    1    1   37 1474    1    5   73 4717]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           3       0.55      0.50      0.53      2507
           4       0.52      0.48      0.50       504
          11       0.29      0.12      0.18       152
          12       0.47      0.32      0.38      1223
          15       0.72      0.74      0.73     10614
          24       0.00      0.00      0.00         6
          33       0.57      0.48   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
